service: blog

package:
  individually: true
  exclude:
    - .git/**
    - node_modules/**
    - .venv/**

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  stage: "dev"
  region: ${file(config.json):REGION}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: "arn:aws:s3:::${file(config.json):BUCKET_NAME}/*"

functions:
  hello:
    handler: handler.generatePresignedUrl
    events:
      - http:
          path: presigned
          method: post
