service: blog

package:
  individually: true
  exclude:
    - .git/**
    - .venv/**

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  stage: "dev"
  region: ${file(config.json):REGION}

  iamRoleStatements:
    - Effect: Allow
      Action: "*"
      Resource: "arn:aws:s3:::${file(config.json):BUCKET_NAME}/*"

functions:
  hello:
    handler: handler.generatePresignedUrl
    events:
      - http:
          path: presigned
          method: post
          cors: true

  copyObjects:
    handler: handler.moveObjects
    events:
      - http:
          path: copy
          method: put
          cors: true
